name: probe_designer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bs4=4.12.2
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - charset-normalizer=2.0.4
  - decorator=5.1.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.15.0
  - ipython=8.13.2
  - jedi=0.18.2
  - jupyter_client=7.3.4
  - jupyter_core=5.3.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numpy-base=1.24.3
  - openpyxl=3.0.9
  - openssl=1.1.1u
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=3.5.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - viennarna=2.3.3
  - wcwidth=0.2.6
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - beautifulsoup4==4.12.2
    - biopython==1.78
    - bottleneck==1.3.5
    - brotlipy==0.7.0
    - cffi==1.15.1
    - cryptography==39.0.1
    - debugpy==1.5.1
    - idna==3.4
    - jupyter-core==5.3.0
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - numexpr==2.8.4
    - numpy==1.24.3
    - pandas==1.5.3
    - pip==23.0.1
    - psutil==5.9.0
    - pyopenssl==23.0.0
    - pysocks==1.7.1
    - pytz==2022.7
    - pyzmq==25.0.2
    - requests==2.29.0
    - setuptools==66.0.0
    - soupsieve==2.4
    - tornado==6.1
    - urllib3==1.26.15
    - wheel==0.38.4